apiVersion: apps/v1
kind: Deployment
metadata:
  name: YOUR_NAME-deployment
  labels:
     deployment: YOUR_NAME-deployment
spec:
  selector:
      matchLabels:
        app: YOUR_NAME-app
  replicas: 2
  template:
    metadata:
      labels:
        app: YOUR_NAME-app
    spec:
      containers:
        - name: bootcamp-app
          image: harbor.tanzuworkshop.com/YOUR_NAME-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
