apiVersion: v1
kind: Pod
metadata:
  name: raman-app
  labels:      
    type: bootcamp                          
    app: raman-app
spec:
  containers:
  - name: bootcamp-app
    image: harbor.tanzuworkshop.com/bootcamp/raman-app
    imagePullPolicy: Always
    ports:
         - containerPort: 8080
    resources:
      limits:
        memory: "250Mi"
      requests:
        memory: "250Mi"
      limits:
        cpu: "250m"
      requests:
        cpu: "250m"
