apiVersion: v1
kind: Pod
metadata:
  name: YOUR-NAME-app
  labels:                                
    app: YOUR-NAME-app
spec:
  containers:
  - name: app
    image: harbor.pcfplatform.com/anz-bootcamp/YOUR-NAME-app:latest
    ports:
         - containerPort: 8080
    resources:
      limits:
        memory: "1000Mi"
      requests:
        memory: "1000Mi"
      limits:
        cpu: "500m"
      requests:
        cpu: "250m"
