apiVersion: v1
kind: Service
metadata:
  name: YOUR_NAME-service
spec:
  selector:
    type: bootcamp
    app: YOUR_NAME-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
