apiVersion: v1
kind: Service
metadata:
  name: YOUR-NAME-lb
spec:
  selector:
    app: YOUR-NAME-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
